### ISSUE TITLE
Tables can get centered if small

### ISSUE THREAD

**Issue by jhand2** [TrustedComputingGroup/pandoc#34]
Small tables are sometimes rendered very small and centered on the page. We should left align all tables and make them take up more space if the cell widths are very small

![Screen Shot 2022-12-19 at 1 52 56 PM](https://user-images.githubusercontent.com/11011105/208531411-f9fd4199-9758-408d-bbdf-73c043ad0b69.png)

**Comment by chrisfenner** [comment]
Tables have changed substantially since 2022; how does your doc's tables look using a more recent container @jhand2?

Pandoc has some opinions about when to shrink the width of a table. If you want to force a table to be wider, you may be able to do so by using [multiline table syntax](https://pandoc.org/chunkedhtml-demo/8.9-tables.html) and using a lot of dashes to "hint" to the parser that you want really wide columns.

**Comment by chrisfenner** [comment]
5203ffcf85b0784d4ca84c2b2105c1da309a0350 normalizes all the table widths!
